pipeline {
    agent any
    
    stages {
        
        stage('Terraform') {

            agent {
                dockerfile {
                    filename 'Dockerfile'
                    dir 'jenkins/terraform-slave'
                    // mount workspace with pulled repository so terraform state is not lost + store secrets in a file.
                    args '-v $WORKSPACE:/var/git -v /home/local/DO/mykhailo.krykunenko/secret:/root/secret'
                }
            }
            
            steps {
                sh 'chmod +x /root/secret/credentials.sh && /bin/sh /root/secret/credentials.sh'
                sh 'ls -lah /var/git'
                sh 'cd /var/git/terraform && terraform init && terraform plan'
                
            }
            
        }
        
    }
}