pipeline {
    agent any
    
    stages {
        
        stage('Terraform') {

            agent {
                dockerfile {
                    filename 'Dockerfile'
                    dir 'jenkins/terraform-slave'
                    args '-v ${PWD}:/var/git'
                }
            }
            
            steps {
                sh 'terraform plan'
            }
            
        }
        
    }
}