pipeline {
    agent any
    
    stages {
        
        stage('Terraform') {
            agent {
                dockerfile {
                    filename 'Dockerfile'
                    dir 'devpro/terraform-slave'
                    args '-v ./:/shared-repo'
                }
            }
            
            steps {
                sh 'echo 123'
            }
            
        }
        
    }
}