version: '3'

services:

  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    networks:
      - net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - net
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
  net:
    external: true