---
- name: Get all RDS instances
  community.aws.rds_instance_info:
  - tags: tag_name_db

- name: Test
  hosts: localhost
  connection: local
  tasks:
    - name: test
      ansible.builtin.shell:
        cmd: echo {{ }}