---

- name: Enable MariaDB
  command: amazon-linux-extras install -y mariadb10.5
  notify: Restart MariaDB

- name: Start the MySQL service
  action: service name=mariadb state=started

- name: Install PHP FPM and dependencies
  yum:
    name: python-pip
    state: latest

- name: Install bottle python package
  pip:
    name: pymysql

- name: update mysql root password for root account
  mysql_user:
    name: root
    login_unix_socket: /var/lib/mysql/mysql.sock
    host: 'localhost'
    password: 12345
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true

